### ISSUE TITLE
docker file to install grafana-mongodb image

### ISSUE THREAD

**Issue by UnCanard14** [ajeje93/grafana-mongodb-docker#3]
Hi ajeje93 is there any way to use a docker-compose.yml file to install your plugin ?
Like this for example:

```
version: "3.7"

services:      
  grafana:
    image: ajeje93/grafana-mongodb
    container_name: grafana-mongodb
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      
volumes:
  grafana-data:
```
Like this grafana installs but I don't see the data source mongo db can you help me?
Sincerely

**Comment by ajeje93** [comment]
Hi, have you tried to use the docker compose file included in the repo?

https://github.com/ajeje93/grafana-mongodb-docker/blob/a022e09b94e05aea1ded862cf196cd09a7f4dbbc/docker-compose.yml

I think you are missing this in the volumes section:
```
- /var/lib/grafana/plugins
```

**Comment by UnCanard14** [comment]
Ah yes that was it thank you very much with this docker-compose.yml I succeeded :+1: 
version: "3.7"

```
services:      
  grafana:
    image: ajeje93/grafana-mongodb
    container_name: grafana-mongodb
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      - /var/lib/grafana/plugins

volumes:
  grafana-data:
```
