### ISSUE TITLE
Unsupported OP_QUERY command: aggregate.

### ISSUE THREAD

**Issue by UnCanard14** [ajeje93/grafana-mongodb-docker#4]
Hi  ajeje93,
Is it possible to have an image based on the fork https://github.com/SiemaApplications/mongodb-grafana that is more up to date ? Because I have an error "`Unsupported OP_QUERY command: aggregate. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal`" due to the version of the npm mongo package being "^3.0.8" when I run this request on timeseries collection:
```
db.measurements.aggregate(
[
    {
        "$project": {
            "name": "$metadata.DevEUI",
            "value": "$temperature",
            "ts": "$timestamp",
            "_id": 0
        }
    }
]
)
```
and that works when my mongo package is at least in "^4.12.1"

Can you do something for me ?
Sincerely

**Comment by ajeje93** [comment]
Hi, I'll try and get back to you

**Comment by ajeje93** [comment]
@UnCanard14 I updated the image with the plugin you suggested, everything seems to work fine.

The only difference (I think it depends on the Grafana version) is that you should do your projections like this:

```
db.measurements.aggregate(
[
    {
        "$project": {
            "yourLabel": "$temperature",
            "time": "$timestamp",
            "_id": 0
        }
    }
]
)
```

Let me know if the new image works for you.

**Comment by UnCanard14** [comment]
I'll look into it when I can and get back to you :)

**Comment by UnCanard14** [comment]
I obviously don't have the Unsupported OP_QUERY error anymore but I do a simple query in grafana:
```
db.temperature.aggregate(
[
    {
        "$project": {
            "_id": 0
        }
    }
]
)
```
I have a "Gateway Timeout" error. I confess that I did not succeed in installing the version without docker image of SiemaApplications...

**Comment by ajeje93** [comment]
Can you share a little bit more about your configuration? I had no problems running the container and the plugin seems to work fine also.

I have a working example over here: https://github.com/ajeje93/speedtest-to-mongodb#docker

There you can find an application writing to MongoDB and the link to a Grafana dashboard to visualize data. I used the container from this repo.

**Comment by UnCanard14** [comment]
ok thank you very much, i will send you my configuration in the evening

**Comment by UnCanard14** [comment]
1. I install my grafana image and mongo db with this docker compose :
  GNU nano 6.2                                                                                  docker-compose.yml                                                                                           
```
version: "3.7"

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  grafana:
    image: ajeje93/grafana-mongodb
    container_name: grafana-mongo
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      - /var/lib/grafana/plugins

volumes:
  dbdata6:
  grafana-data:

```
2. With " mongodb compass " I connect to my base
3. I create a base with mongosh `use mydatabse`
4. I am making a [time series collection](https://www.mongodb.com/docs/v5.3/core/timeseries-collections/)
```
db.createCollection(
    "weather",
    {
       timeseries: {
          timeField: "timestamp",
          metaField: "metadata",
          granularity: "hours"
       }
    }
)
```
5.I import my temperature file " temperature.json " (which are the data sent by my sensors) i have to shorten the file for the example:
```
[{
  "timestamp": {
    "$date": "2023-04-24T14:47:33.489Z"
  },
  "metadata": {
    "DevEUI": "20635F0221000014"
  },
  "_id": {
    "$oid": "64469684410ecc8270e76e38"
  },
  "temperature": 21.8
},{
  "timestamp": {
    "$date": "2023-04-24T14:48:47.850Z"
  },
  "metadata": {
    "DevEUI": "20635F01080008E4"
  },
  "_id": {
    "$oid": "644696d0410ecc8270e76e39"
  },
  "temperature": 29.4
},{
  "timestamp": {
    "$date": "2023-04-24T14:48:56.459Z"
  },
  "metadata": {
    "DevEUI": "20635F01080010D6"
  },
  "_id": {
    "$oid": "644696d7410ecc8270e76e3a"
  },
  "temperature": 29.9
}]
```
6.With mongogsh this request works
```
db.weather.aggregate(
	[
	    {
	        "$project": {
	            "name": "$metadata.DevEUI",
	            "value": "$temperature",
	            "ts": "$timestamp",
	            "_id": 0
	        }
	    }
	]
)
```

7. On grafana I add my "data source" with 
`http://localhost:3333`
`mongodb://localhost:27017/`
`mydatabase`

8.When I try with the same query in grafana I get the error "Query error
Gateway Timeout "
