### ISSUE TITLE
I receive "Bad gateway"

### ISSUE THREAD

**Issue by gfenza** [ajeje93/grafana-mongodb-docker#8]
I receive "Bad gateway" when I save and test the data source. 
MongoDB version is 5.0.7 and it is installed locally on the host of docker containers.

**Comment by ajeje93** [comment]
Hi, i tried with this `docker-compose.yml`:

```yml
version: "3"
services:
  grafana:
    image: ajeje93/grafana-mongodb
    restart: always
    volumes:
     - ./data:/var/lib/grafana
     - /var/lib/grafana/plugins
    ports:
     - 3000:3000
    
  mongodb:
    image: mongo:5.0.7
    restart: always
    ports:
     - 27017:27017
```

and I configured the plugin like this:

![screencapture-localhost-3000-connections-datasources-edit-c866b799-00d5-4c30-9c4c-a39b27b18e1b-2023-11-01-17_11_44](https://github.com/ajeje93/grafana-mongodb-docker/assets/11637841/bbe6a5e9-e878-470c-9cb9-43a8e9980b3a)

and everything looks fine.

Some people had the same issue as you but most of the time the problem is misconfiguration: https://github.com/ajeje93/grafana-mongodb-docker/issues/5#issuecomment-1598599998

The `URL` field under `HTTP` should always be configured with `http://localhost:3333` as the plugin to connect with MongoDB is installed inside the container.

If you have MongoDB installed in your Docker host you should put `mongodb://host.docker.internal:27017` in the `MongoDB URL` field.

Can you share a little bit more about your configuration?
